CC=gcc
YFLAG=-d
FNAME=??
EXE=myparser

compile: scanner parser
	${CC} lex.yy.c y.tab.c -o ${EXE}

scanner:
	lex ${FNAME}.l

parser: 
	yacc ${YFLAG} ${FNAME}.y

test: compile
	./${EXE} < input/advance_if_else.go

clean:
	rm ${EXE} y.tab* lex.* y.output